### ISSUE TITLE
画像投稿機能の追加

### ISSUE THREAD

**Issue by Rintaro196** [Rintaro196/game_award#11]
## Task
画像を投稿できるようにする。
カラムは既に存在している。

## TODO
- [x] gem `carrierwave'を導入
- [x] アップローダーとカラムを紐づける
- [x] ストロングパラメーターに`:image`を追加
- [x] ビューファイルに反映
　　画像の投稿がない場合はデフォルト画像を設定(sample.png)

## 参考記事
https://qiita.com/oden-09/items/5b494ff9abe7f2734b3e

**Comment by kzkio114** [comment]
終わりました〜！
こちらにも、一応コメントしておきますね！！
